### ISSUE TITLE
Investigate OCDT StressGenerator CLI

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-Server-Administration-Tool#2]
Investigate and document functionality of OCDT StressGenerator CLI tool to be ported to CDP4SAT.

**Comment by adrianchivu** [comment]
## Description
Tool to assist in the simulation of concurrent multi-user testing. For the given engineering model, it first deletes all
element definitions if this was requested. Subsequently it adds, at the given regular time interval, a new element definition
with some parameters. The parameters are owned by different domains of expertise, selected pseudo-randomly from the
active domains in the given engineering model.

## Configurations options for the 'Command Line Tools'

### interval
* Numeric type
* Default value: 5
* Represents test data generation time interval in second

### n-objects
* Numeric type
* Default value: 50
* The number of test objects to be generated. Maximum allowed is 500. 
* Zero or negative means generate maximum allowed number.

### element-name
* String type.
* Default value: Element.
* Represents the first part of generated element definition name.

### element-short-name
* String type.
* Represents the first part of generated element definition short name.

### delete-all-elements
* Boolean type
* Set "true" On start-up, first will delete all existing element definitions in the engineering model.

### server
* Required
* Default value: http://localhost:1234
* Represents the URI of OCDT server to connect to

### model
* Required. 
* Represents the Short name of the engineering model to process. 
* Asterisk "*" means: process all engineering models.
* The engineering model short name should start with "Stresser" to avoid
accidental modifications.

### help
* Display this help screen.

### version
* Display version information.

**Comment by alexatrhea** [comment]
ok, looks good
