### ISSUE TITLE
Check if the first Syncer implementation allows model synchronization

### ISSUE THREAD

**Issue by adrianchivu** [RHEAGROUP/CDP4-Server-Administration-Tool#68]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-Server-Administration-Tool
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/issues) and [closed](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In the source code of the first Syncer implementation(OCDT CommandLineTools) version we found this enumeration:
<code>public enum ThingType</code>
<code>{</code>
<code>&nbsp;&nbsp;// EngineeringModel,</code>
<code>&nbsp;&nbsp;SiteReferenceDataLibrary,</code>
<code>&nbsp;&nbsp;DomainOfExpertise</code>
<code>}</code>
and we would like to clarify if the synchronization mechanism worked/should work only with SiteReferenceDataLibrary & DomainOfExpertise objects.

### System Configuration

- [ ] CDP4-Server-Administration-Tool version:
- [ ] Environment (Operating system, version and so on):
- [ ] .NET Framework version:
- [ ] Additional information:

**Comment by lxatrhea** [comment]
No added value in doing this.
