### ISSUE TITLE
SAT migration should migrate all iterations, not just the last one

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-Server-Administration-Tool#97]
### Description
It seems like the SAT migration process only takes into account the last iteration, instead of migrating all iterations present; this needs to be changed ASAP.

**Comment by cozminvelciu** [comment]
Issue created as a result of [this](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/issues/93).

**Comment by adrianchivu** [comment]
Related with https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues/167
